spring.application.name=School Management
server.port=5050
spring.datasource.url=jdbc:postgresql://localhost:5432/school
spring.datasource.username=postgres
spring.datasource.password=Abdoul
spring.data.jdbc.dialect=postgresql


logging.level.root=ERROR
logging.level.org.school=INFO
logging.level.org.springframework.boot.web.embedded.tomcat.TomcatStarter=INFO


